#!/bin/bash
# Quick start script for testing parallel commenting

echo "=========================================="
echo "🚀 Параллельное комментирование - Быстрый старт"
echo "=========================================="
echo ""
echo "Система полностью готова к тестированию!"
echo ""
echo "📋 ТЕСТОВЫЕ КАНАЛЫ:"
echo "   @AIGIRLSARTS"
echo "   @testertesti"
echo "   @testtestista"
echo "   @testingmana"
echo "   @chiptesterchip"
echo ""
echo "🎯 ЧТО РЕАЛИЗОВАНО:"
echo "   ✅ Каждый воркер обрабатывает ВСЕ каналы циклически"
echo "   ✅ Offset для распределения нагрузки"
echo "   ✅ Детальное логирование (cycle, step, account)"
echo "   ✅ Автоматическая ротация после завершения цикла"
echo ""
echo "🔧 КОМАНДЫ ДЛЯ ТЕСТА В БОТЕ:"
echo ""
echo "1. Настроить тестовый режим:"
echo "   /testmode on"
echo "   /testchannels @AIGIRLSARTS @testertesti @testtestista @testingmana @chiptesterchip"
echo ""
echo "2. Настроить параллельность (2 аккаунта):"
echo "   /setparallel 2"
echo ""
echo "3. Проверить активные аккаунты:"
echo "   /listaccounts"
echo "   (должно быть минимум 2 с ✅ active)"
echo ""
echo "4. Запустить:"
echo "   /startmon"
echo ""
echo "📊 ЧТО ИСКАТЬ В ЛОГАХ:"
echo ""
echo "   WORKER STARTED: account=+XXX, parallel_idx=1/2"
echo "   WORKER STARTED: account=+YYY, parallel_idx=2/2"
echo ""
echo "   COMMENT: account=+XXX -> channel=@AIGIRLSARTS, cycle=1, step=1"
echo "   COMMENT: account=+YYY -> channel=@testertesti, cycle=1, step=1"
echo ""
echo "   WORKER FINISHED CYCLE: account=+XXX, cycle=1"
echo "      Commented channels: [@AIGIRLSARTS, @testertesti, ...]"
echo ""
echo "=========================================="
echo "✅ Готово к запуску!"
echo "=========================================="
